### PR TITLE
Date Time Picker: Added Placeholder Support

### PR DESCRIPTION
**Pull request by rowellx68**

### CODE REVIEW

**Comment by ghiscoding** [comment]
Thanks for the PR, looking at it, can I assume that you ran `gulp build` and `gulp lint` on the plugin?

**Comment by rowellx68** [comment]
Yes, `gulp build`, `gulp lint`, and `gulp prepare-release`. Might've been a bit trigger happy with `gulp prepare-release` tbh.

**Comment by ghiscoding** [comment]
Great, I will merge & publish a release by the end of the day. Thanks for the PR :)

**Comment by ghiscoding** [comment]
Merged and published on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker), thanks again 👍

**Pull request merged**
