### PR TITLE
Support FontAwesome 5 with DateTimePicker

### PR DESCRIPTION
**Pull request by Cali03**
Hi,

Here you have my changes for support FontAwesome 5.
I change the calendar icon to calendar-alt, i prefer it :)

Thanks

### CODE REVIEW

**Comment by ghiscoding** [comment]
@Cali03 
Have you tested it? 
I can merge it a bit later today but I won't have time to test anything since I'm going in vacation tomorrow.

**Comment by Cali03** [comment]
Hi @ghiscoding ,

Of course i have tested it. it work great just need to set config.extra.iconBase = 'font-awesome-5'

It's not an urgent question for me so you can merge it when you come back.

Enjoy your vacation.

**Comment by ghiscoding** [comment]
I'll merge it this evening and push a release, thanks for confirming

**Comment by ghiscoding** [comment]
You missed a curly brace closing [here](https://github.com/Cali03/Aurelia-Bootstrap-Plugins/blob/2eadea5970f67ca814958fa64b9384e5a33e5c2e/aurelia-bootstrap-datetimepicker/src/abp-datetime-picker.js#L99) which I had to fix to make it build properly.

It is now release under version `1.2.0` on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)

**Comment by Cali03** [comment]
Hi,

I just copied the else ... 
Sorry ...
Fucking copy & paste 

Thanks

**Pull request merged**
