### PR TITLE
fix(select) issue #68 Optgroup doesn't work if there are fewer option…

### PR DESCRIPTION
**Pull request by jmurphy-riskexec**
…s than the group index

### CODE REVIEW

**Comment by jmurphy-riskexec** [comment]
I added another commit which fixes two more `selected(Value|Item)Changed` infinite loop cases, and ignores disabled options when setting `selectedValue` or `selectedItem`

**Comment by ghiscoding** [comment]
Thanks it will take me couple days to test it out, so please be patient. I always welcome PR :)

**Comment by jmurphy-riskexec** [comment]
Great, no hurry on my part.  Thanks for the great plugin.  It's very useful

**Comment by ghiscoding** [comment]
Looks ok except that running the linter with `gulp lint` shows up few warnings. The most common one is that it requires all line to finish with semicolons. I will merge and push another commit to address these warnings

**Pull request merged**
